# Generated by Django 4.2.2 on 2023-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLSCNetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=12)),
                ('port_number', models.CharField(max_length=30)),
            ],
        ),
    ]
