# Generated by Django 4.2.2 on 2023-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=200, verbose_name='Satellite Name')),
                ('longitude', models.CharField(max_length=200, verbose_name='Longitude')),
                ('local_frequency', models.CharField(max_length=200, verbose_name='Local Frequency')),
                ('rx_polarization', models.CharField(max_length=200, verbose_name='Rx Polarization')),
                ('tx_polarization', models.CharField(max_length=200, verbose_name='Tx Polarization')),
                ('time', models.CharField(max_length=200, verbose_name='Time')),
            ],
        ),
    ]
